name: 03 - Docker Build 

on:
  push:
    branches: [main , master]
  workflow_dispatch:

jobs:
  docker-build:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build (no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: false
          tags: local/giga:latest
          
          
